### ISSUE TITLE
Extend the `set-*` mutation helpers.

### ISSUE THREAD

**Issue by currentoor** [untangled-web/client#2]
The built in `untangled.client.mutations/set-integer!` is pretty handy.

Wouldn't a `set-bigdec!`, `set-bigint!`, and `set-instant!` be useful also?

I can submit a PR for them if you'd like.

Edit: I don't think big decimals or big integers are supported. Perhaps you can think of a work around? Or `set-double!` at the very least?

**Comment by awkay** [comment]
Well, those functions are meant for UI-only attributes and form filling. You should always be using top-level abstract transactions for most of your work,...twiddling values should be for things like checkboxes and form field inputs. I'm fine with adding more type coercion, and a PR is fine. Instant makes sense, but how are you thinking of doing bigint etc since cljs does not have support for them?

**Comment by currentoor** [comment]
@awkay upon more research it looks like I'll only be able to add `set-double!` and `set-instant!`.

**Comment by awkay** [comment]
Sure, feel free....

**Comment by awkay** [comment]
Sounds good.

**Comment by awkay** [comment]
Feel free to submit a PR for these if you ever make them. I'm closing this since it isn't a bug.
