### ISSUE TITLE
load-field-action when subquery has ident results in not-found in app state under the field

### ISSUE THREAD

**Issue by jasonjckn** [untangled-web/client#29]
+the server must returns nothing for the ident to reproduce this

jasonjckn [3:27 PM]  
it's weird to see anything at all in the global state at [:search :tab :hits [:search :tab]] for the ident [:search :tab], because if I actually returned a value from the server for [:search :tab] it would not exist in the global state at the path [:search :tab :hits ...] the data would be merged into [:search :tab], and then when om.next computes the props for the query [... [:search :tab]] it would fill it in

[3:27]  
but as it stands I see [:search :tab] not found in the global state under hits

**Comment by awkay** [comment]
I'm not sure what to do about this. I'm having trouble figuring out if we should even bother sending such queries to a server (e.g. auto-elide idents as properties), tell users to use `:without` (and ensure an ident works in `:without`).

We could also modify our merge routine to sort-of support this, but what do we do if you return nothing. This is related to issue #39, in that I'm not sure what to do about that one either.

Here's the problem:

Anything in a table can be referred to in the general graph. If you return nothing from the server, but you asked for the item, then technically you're indicating that the item "disappeared" from the server. This implies that you should delete it from the app state database; however, to do that properly you'd have to clean out all of the ident links in the graph and remove the item from the table. That is almost certainly something the developer would not necessarily appreciate, but if it is predictable, they would at least understand.

Another alternative is to change the merge algorithm to overwrite the object with a map whose values (all except for the value matching the ID of the ident) with something like "DELETED" so that at least you'd have some chance of seeing the problem instead of mysterious disappearances.

That, however, isn't so great, because you could then run into runtime type errors when you try to, say, treat a string "DELETED" as some other thing, like a js/Date or vector.

My leaning is to change the mark/sweep algorithm so that it takes no action on merging nested idents, or change the plumbing to automatically treat raw idents like this like :ui prefixed attributes and not send them at all. 

Do we really want ident-based requests to the server in the middle of the queries? I mean, technically it is legal, but it sorta breaks other rules: like the UI should ask for the specific details it wants, and also should not ask for a UI-specific concern on the server (which [:search :tab] obvoiusly is).

**Comment by awkay** [comment]
@jasonjckn how did you work around this? Did you try `:without` on an ident?

**Comment by jasonjckn** [comment]
In the use case I had at the time it was a UI-specific concern, and so "treat raw idents like this like :ui prefixed" fits that particular use case. I haven't had the time to test `:without` yet, mostly because om.next still works even with `{[:search :tab] ::not-found, ...}` in the app-state, the correct props are still passed to this component e.g. `{[:search :tab] {.. correct value within table ..}}` so I haven't been pressured to spend more time on this yet. So when I filed this issue it was more cosmetic annoyance of just seeing `::not-found` in app state, but functionally the props were fine. 

I don't have any use cases in mind for this, I haven't yet worked with idents on the server, if that's a concept in untangled then it shouldn't matter whether they appear in subquery, or root query IMO.  On the other hand if idents never reach the server in any context, then it makes sense to strip them like `:ui`. My knowledge is limited here, in my own use case, currently idents are just client-side, the server side sends blobs of data that get normalized into ident. 

> "then technically you're indicating that the item "disappeared" from the server. This implies that you should delete it from the app state database; however, to do that properly you'd have to clean out all of the ident links in the graph and remove the item from the table"

Or just set the table value to `nil`

Looking towards the future I was considering doing data normalization with queries like `{[:search :tab] (get-query SearchTab)}` when server returns `{[:search :tab] {.. blob ..}}` if this stops working that worries me, but not sure if it's a deal breaker.  I don't care so much about "DELETED" case, just doing nothing is fine with me.

**Comment by awkay** [comment]
I'm going to consider this to be something you can work around, and close it.
