### ISSUE TITLE
Enhancement: Make it possible to have load-data place the load marker in custom app-state locations

### ISSUE THREAD

**Issue by gardnervickers** [untangled-web/client#43]
If I have a component with the query
`[:a :b :c]`
and run a `data-fetch/load-data` against it with an `:ident` specified, the app state while the data load is going on looks like:
`[:a ... :b ... :c ... nil <fetch marker>]`. 

I believe this is a bug with the `data-path` function. 

**Conversation with @egracer** 
yeah. not sure if it’s a bug or not but it appears to be an issue with the data-path function that you linked me

[9:55]  
it assumes that a load-field is happening, whereas your case is closer to to load-fields (plural)

[9:56]  
so the `field` key may be empty but the `query` key may be present

[9:56]  
makes me think that instead of having a special `field` key in the data state, that we should just put it under `query`

[9:57]  
I’ll have to do some digging to see how / if to fix this but don’t have time at the moment. @gardnervickers can you file an issue and copy this little 5 line rant into it?

**Comment by awkay** [comment]
Our implementation currently places the load marker based on the top-level keyword in the query for `load-data`. This probably doesn't make a lot of sense for a lot of cases, since you can trigger load-data from anywhere, but you might have a specific place you'd like to show the "spinner" for that _particular_ load (e.g. as an attribute of a component that is on-screen and will receive the data from a post-mutate after the load).

The primary difficulty is ensuring that the load marker gets removed, and that the removal doesn't hose anything.

**Comment by awkay** [comment]
It occurs to me, as I write this, that the behavior of load-field is often what you want, but not targeted specifically at a component you're in. Sometimes it makes sense to load a query directly into the root of app state, but more often it might just make sense to target the marker AND the result at a field on some arbitrary db table object's field by explicit ident. That case is not currently easy.

I'm thinking through the API. This is a central part of the story, so I want to end up with a simple, and easy-to-use interface.

**Comment by awkay** [comment]
This is in 0.6.0-SNAPSHOT on clojars. I've deprecated load-data and load-data-action, and use load and load-action instead. There is a new argument: `target`. I have not tested that I didn't break the old API yet.
